[project]
name = "livedata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "openai>=1.78.1",
    "pandas>=2.2.3",
<<<<<<< HEAD
    "scikit-learn>=1.6.1",
=======
>>>>>>> ff5e4748cad2fc3adabf7bd6b8e403b608a8c037
    "seaborn>=0.13.2",
    "streamlit>=1.45.1",
]
